name: Test build

on:
  push:
    branches: [
      "stable",
      "dev-stable"
    ]
  pull_request:
    branches: [
      "stable",
      "dev-stable"
    ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Toolchain
        uses: Egor00f/install-kolibrios-toolchain-action@main

      - name: Install depends
        run: sudo apt install fasm

      - name: KolibriOS repo
        run: |
          cd ${{ github.workspace }}/../
          git clone https://git.kolibrios.org/KolibriOS/kolibrios.git
      
      - name: Configure CMake
        run: |
          cd ${{ github.workspace }}
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/toolchain.cmake

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --target all --config ${{env.BUILD_TYPE}}
